go: switch to go 1.19 due to compile error
```
Error: ../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.15.1/trace/provider.go:78:24: undefined: atomic.Pointer
Error: ../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.15.1/trace/provider.go:80:20: undefined: atomic.Bool
note: module requires Go 1.19
```